# -------
# Library
# -------

library:
  name: ComposeChangelog
  api: 21
  github: MFlisar/ComposeChangelog
  maven: io.github.mflisar.composechangelog
  maven-main-library: core
  multiplatform: true
  screenshots:
    - name: Changelog
      images:
        - ./screenshots/overview.jpg
  branch: main
  demo: true

# ------------
# Dependencies
# ------------

# optional
dependencies:
  compose:
    cmp: 1.7.3
    compose: 1.7.5
    material3: 1.3.1
    experimental: false

# -------------
# Module
# -------------

# GRUPPEN - optional: nur bei mehreren Modulen benötigt!
groups:
  - name: core
    label: Core
    gradle-comment: core 
  - name: modules
    label: Modules
    gradle-comment: statesaver modules

modules:
  - name: core
    group: core
    description: the core module to show a changelog
    optional: false
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []
  - name: statesaver-preferences
    group: modules
    description: saves the state of the last shown changelog inside a preference file
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: [ ]
  - name: statesaver-kotpreferences
    group: modules
    description: saves the state of the last shown changelog inside a preference file using my KotPreferences library
    optional: true
    platforms:
      android: true
      ios: false
      jvm: true
      info:
    dependencies:
      - name: KotPreferences
        link: https://github.com/MFlisar/KotPreferences
        version: 0.7.2