# -------
# Library
# -------

library:
  name: ComposeChangelog
  api: 21
  github: MFlisar/ComposeChangelog
  maven: io.github.mflisar.composechangelog
  maven-main-library: core
  multiplatform: true
  platforms:
    - jvm
    - android
  screenshots: 
    - name: core
      images:
        - ./screenshots/core/overview.jpg
  branch: master
  demo: true

# ------------
# Dependencies
# ------------

dependencies:
  compose-multiplatform: 1.7.3 # https://github.com/JetBrains/compose-multiplatform/releases
  jetpack-compose-runtime: 1.7.6 # https://developer.android.com/jetpack/androidx/releases/compose-runtime
  jetpack-compose-material3: 1.3.1 # https://developer.android.com/jetpack/androidx/releases/compose-material3
  experimental: false

# ------------
# Groups
# ------------

groups:
  - name: core
    label: Core
    gradle-comment: core
  - name: modules
    label: Modules
    gradle-comment: dialog modules
  - name: gradle-plugin
    label: Gradle Plugin
    gradle-comment: gradle plugin

# ------------
# Modules
# ------------

modules:
  - name: core
    group: core
    description: provides all the basic classes and composables to show a changelog
    optional: false
    platforms:
      - jvm
      - android
    platforms-info: ""
    dependencies: []
  - name: gradle-plugin
    group: gradle-plugin
    description: a gradle plugin that provides common functions for gradle files
    optional: true
    platforms: []
    platforms-info: this is a gradle plugin only
    dependencies: []
  - name: gradle-plugin-shared
    group: gradle-plugin
    description: a gradle plugin that provides common function
    optional: true
    platforms:
      - jvm
      - android
      - macos
      - ios
    platforms-info: no need to include this manually
    dependencies: []
  - name: statesaver-kotpreferences
    group: modules
    description: provides a simple state saver based on KotPreferences
    optional: true
    platforms:
      - jvm
      - android
    platforms-info: ""
    dependencies: []
  - name: statesaver-preferences
    group: modules
    description: provides a simple state saver based on jetpack preferences
    optional: true
    platforms:
      - jvm
      - android
    platforms-info: ""
    dependencies: []