[versions]

# mflisar
kotpreferences =        "1.0.3"
kmp-parcelize =         "1.0.0"
kmp-gradle-tools =      "1.4.5"

accompanist = 			"0.37.3"
htmlconverter =         "1.1.0"

[plugins]

kmp-gradle-tools-gradle-plugin =    { id = "io.github.mflisar.kmp-gradle-tools.gradle-plugin",              version.ref = "kmp-gradle-tools" }

[libraries]

# mflisar
kotpreferences-core =               { module = "io.github.mflisar.kotpreferences:core", 					version.ref = "kotpreferences" }
kotpreferences-storage-datastore =  { module = "io.github.mflisar.kotpreferences:storage-datastore",      	version.ref = "kotpreferences" }
kotpreferences-extension-compose =  { module = "io.github.mflisar.kotpreferences:extension-compose",      	version.ref = "kotpreferences" }
kmp-parcelize =                     { module = "io.github.mflisar.parcelize:library", 	                    version.ref = "kmp-parcelize" }
kmp-gradle-tools-scripts =          { module = "io.github.mflisar.kmp-gradle-tools:scripts",                version.ref = "kmp-gradle-tools" }
kmp-gradle-tools-docs =             { module = "io.github.mflisar.kmp-gradle-tools:docs",                   version.ref = "kmp-gradle-tools" }

drawablepainter = 		            { module = "com.google.accompanist:accompanist-drawablepainter", 		version.ref = "accompanist" }
htmlconverter =                     { module = "be.digitalia.compose.htmlconverter:htmlconverter", 			version.ref = "htmlconverter" }