[versions]

moko-parcelize =        "0.9.0"
accompanist = 			"0.36.0"

# mflisar
kotpreferences =        "0.8.0"
toolbox =               "2.4.5" # demo app only!

htmlconverter =         "1.0.3"

[libraries]

moko-parcelize =                    { module = "dev.icerock.moko:parcelize", 		                        version.ref = "moko-parcelize" }
drawablepainter = 		            { module = "com.google.accompanist:accompanist-drawablepainter", 		version.ref = "accompanist" }

# mflisar
kotpreferences-core =               { module = "io.github.mflisar.kotpreferences:core", 					version.ref = "kotpreferences" }
kotpreferences-storage-datastore =  { module = "io.github.mflisar.kotpreferences:storage-datastore",      	version.ref = "kotpreferences" }
kotpreferences-extension-compose =  { module = "io.github.mflisar.kotpreferences:extension-compose",      	version.ref = "kotpreferences" }
toolbox-demo-app =                  { module = "io.github.mflisar.toolbox:android-demo-app", 			    version.ref = "toolbox" }

htmlconverter =                     { module = "be.digitalia.compose.htmlconverter:htmlconverter", 			version.ref = "htmlconverter" }